/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;

import modelo.Inventario;
import modelo.Usuario;
import InterfazGrafica.VentanaAnimales;
import InterfazGrafica.Login;
import modelo.Usuarios;
/**
 *
 * @author akzelini
 */
public class IgInventario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(IgInventario.class.getName());

    /**
     * Creates new form IgInventario
     * 
     */
    private Inventario inventario;
    private Usuarios usuarios;
    
    
    private Usuario usuario;
    public IgInventario(Inventario inventario, Usuario usuario, Usuarios usuarios) {
        initComponents();
    this.inventario = inventario;
    this.usuario = usuario;
    this.usuarios = usuarios;

    if (!usuario.getRol().equals("admin")) {
        BtnAgEmpl.setVisible(false);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        BtnAnim = new javax.swing.JButton();
        BtnCom = new javax.swing.JButton();
        BtnPlan = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BtnAgEmpl = new javax.swing.JButton();
        BtnCerrarSesion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Inventario");

        jLabel2.setText("Animales");

        jLabel3.setText("Comida");

        jLabel4.setText("Plantas");

        BtnAnim.setText("Ingresar");
        BtnAnim.addActionListener(this::BtnAnimActionPerformed);

        BtnCom.setText("Ingresar");

        BtnPlan.setText("Ingresar");

        jLabel5.setText("Agregar empleado");

        BtnAgEmpl.setText("Ingresar");
        BtnAgEmpl.addActionListener(this::BtnAgEmplActionPerformed);

        BtnCerrarSesion.setText("Cerrar sesion");
        BtnCerrarSesion.addActionListener(this::BtnCerrarSesionActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(BtnCom)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(BtnPlan)
                                .addGap(161, 161, 161)
                                .addComponent(BtnCerrarSesion))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(BtnAnim))
                                .addGap(69, 69, 69)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(BtnAgEmpl))
                                    .addComponent(jLabel5)))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(436, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel5))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnAnim)
                            .addComponent(BtnAgEmpl))
                        .addGap(36, 36, 36)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(BtnCom)
                        .addGap(36, 36, 36)
                        .addComponent(jLabel4)
                        .addGap(27, 27, 27)
                        .addComponent(BtnPlan)
                        .addContainerGap(58, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnCerrarSesion)
                        .addGap(35, 35, 35))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAnimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAnimActionPerformed
            VentanaAnimales v = new VentanaAnimales(inventario, usuario);
            v.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAnimActionPerformed

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
            Login login = new Login();
login.setVisible(true);
this.dispose();



        // TODO add your handling code here:
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed

    private void BtnAgEmplActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgEmplActionPerformed
VentanaEmpleados v = new VentanaEmpleados(usuarios, usuario);
v.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_BtnAgEmplActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgEmpl;
    private javax.swing.JButton BtnAnim;
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JButton BtnCom;
    private javax.swing.JButton BtnPlan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
