package InterfazGrafica;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
import javax.swing.table.DefaultTableModel;
import modelo.Animal;
import modelo.Inventario;
import javax.swing.table.DefaultTableModel;
import modelo.Animal;
import javax.swing.JOptionPane;
import modelo.Animal;
import modelo.Usuario;
import modelo.PrecioInvalidoException;  


/**
 * 
 * 
 *
 * @author akzelini
 */
public class VentanaAnimales extends javax.swing.JFrame {
    
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaAnimales.class.getName());
private Inventario inventario;
private Usuario usuario;


    /**
     * Creates new form VentanaAnimales
     */
    public VentanaAnimales(Inventario inventario, Usuario usuario) {
        
     initComponents();
     setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    this.inventario = inventario;
    this.usuario = usuario;
    cargarTabla();
    configurarPermisos();

              
    
       
       
  
    }
           private void cargarTabla() {
               
               
               
    String[] columnas = {"ID", "Nombre", "Edad", "Peso", "Precio"};

    
    
    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

    for (Animal a : inventario.getAnimales()) {
        Object[] fila = {  a.getId(),
    a.getNombre(),
    a.getEdad(),
     a.getPeso() + "kg",
  "$" +  a.getPrecio()
   
        
        };
        modelo.addRow(fila);
    }

    jTable1.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        BtnModificar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Edad", "Peso", "Precio"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Agregar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jButton2.setText("Eliminar");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        BtnModificar.setText("Modificar");
        BtnModificar.addActionListener(this::BtnModificarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 537, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(BtnModificar, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(17, 17, 17)
                .addComponent(BtnModificar)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

    try {

        int id = Integer.parseInt(
                JOptionPane.showInputDialog("ID")
        );

        String nombre = JOptionPane.showInputDialog("Nombre");

        int edad = Integer.parseInt(
                JOptionPane.showInputDialog("Edad")
        );

        double peso = Double.parseDouble(
                JOptionPane.showInputDialog("Peso")
        );

        double precio = Double.parseDouble(
                JOptionPane.showInputDialog("Precio")
        );

        if (precio < 0) {

            throw new PrecioInvalidoException(
                    "El precio no puede ser negativo"
            );
        }

        inventario.agregarAnimal(
                new Animal(id, nombre, edad, peso, precio)
        );

        inventario.guardarEnArchivo();

        cargarTabla();

    } catch (PrecioInvalidoException e) {

        JOptionPane.showMessageDialog(
                this,
                e.getMessage()
        );

    } catch (NumberFormatException e) {

        JOptionPane.showMessageDialog(
                this,
                "Ingresa valores válidos"
        );
    }       // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
int fila = jTable1.getSelectedRow();

    if (fila >= 0) {

        int id = Integer.parseInt(
                jTable1.getValueAt(fila, 0).toString()
        );

        inventario.eliminarAnimal(id);

        inventario.guardarEnArchivo();

        cargarTabla();

    } else {

        JOptionPane.showMessageDialog(this, "Selecciona una fila");
    }

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnModificarActionPerformed
int fila = jTable1.getSelectedRow();

    if (fila >= 0) {

        int id = Integer.parseInt(
                jTable1.getValueAt(fila, 0).toString()
        );

        String nombre = JOptionPane.showInputDialog("Nuevo nombre");

        int edad = Integer.parseInt(
                JOptionPane.showInputDialog("Nueva edad")
        );

        double peso = Double.parseDouble(
                JOptionPane.showInputDialog("Nuevo peso")
        );

        double precio = Double.parseDouble(
                JOptionPane.showInputDialog("Nuevo precio")
        );

        inventario.modificarAnimal(
                id,
                nombre,
                edad,
                peso,
                precio
        );

        cargarTabla();

    } else {

        JOptionPane.showMessageDialog(
                this,
                "Selecciona un animal"
        );
    }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnModificarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       
    }
private void configurarPermisos() {
    if (!usuario.getRol().equals("admin")) {
        jButton1.setEnabled(false);
    }
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnModificar;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
