/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;
import javax.swing.table.DefaultTableModel;
import modelo.Animal;
import modelo.Inventario;
import javax.swing.table.DefaultTableModel;
import modelo.Animal;
import javax.swing.JOptionPane;
import modelo.Animal;
import modelo.Usuario;
import modelo.Usuarios;
import java.util.ArrayList;
import modelo.Empleado;
import modelo.Agricultor;
import modelo.Veterinario;


/**
 *
 * @author akzelini
 */

public class VentanaEmpleados extends javax.swing.JFrame {
    private Usuarios usuarios;
private Usuario usuarioActual;
private ArrayList<Empleado> empleados = new ArrayList<>();
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaEmpleados.class.getName());

    /**
     * Creates new form VentanaEmpleados
     */
    public VentanaEmpleados(Usuarios usuarios, Usuario usuarioActual) {
    initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    this.usuarios = usuarios;
    this.usuarioActual = usuarioActual;
    empleados.add(new Agricultor(1, "Rey David"));
empleados.add(new Veterinario(2, "Astrid Robinson"));

    if (!usuarioActual.getRol().equals("admin")) {
        jButton1.setEnabled(false);
    }
    cargarTabla();
}
  private void cargarTabla() {
    String[] columnas = {"ID", "Nombre", "Trabajo", "Contraseña"};

    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

  for (Empleado e : empleados) {

    String pass = "";

    if (e instanceof Agricultor) {
        pass = "cultivos123";
    }

    if (e instanceof Veterinario) {
        pass = "animales123";
    }

    Object[] fila = {
        e.getId(),
        e.getNombre(),
        e.getTrabajo(),
        pass
    };

    modelo.addRow(fila);
}

    jTable1.setModel(modelo);
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Agregar");
        jButton1.addActionListener(this::jButton1ActionPerformed);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Trabajo", "Contraseña"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Gestion de empleados");

        jButton2.setText("Despedir");
        jButton2.addActionListener(this::jButton2ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap(595, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addComponent(jButton2))
                        .addGap(62, 62, 62))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(89, 89, 89))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  String nombre = JOptionPane.showInputDialog("Usuario");
    String pass = JOptionPane.showInputDialog("Contraseña");

    int id = usuarios.getListaUsuarios().size() + 1;

    usuarios.agregarUsuario(new Usuario(id, nombre, pass, "empleado"));

    cargarTabla();
    usuarios.guardarEnArchivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int fila = jTable1.getSelectedRow();

if (fila == -1) {
    JOptionPane.showMessageDialog(this, "Selecciona un empleado");
    return;
}

int id = (int) jTable1.getValueAt(fila, 0);

usuarios.eliminarUsuario(id);

cargarTabla();

if (!usuarioActual.getRol().equals("admin")) {
    jButton1.setEnabled(false);
}
 jButton2.setEnabled(false);
 
 




        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
