/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package InterfazGrafica;
import java.util.Random;
import modelo.Inventario;
import modelo.Cultivos;
import modelo.Animal;
import modelo.Cultivo;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author JC
 */
public class VentanaVender extends javax.swing.JFrame {
    
    private Inventario inventario;
private Cultivos cultivos;
        private double dinero;
private double porcentajeMercado;
 private static final java.util.logging.Logger logger =
        java.util.logging.Logger.getLogger(VentanaVender.class.getName());


    public VentanaVender(Inventario inventario, Cultivos cultivos, double dinero) {
    initComponents();
    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    this.inventario = inventario;
    this.cultivos = cultivos;
    this.dinero = dinero;

    actualizarPrecios();
    cargarTabla();
    actualizarIndicadorMercado();
}


    /**
     * Creates new form VentanaVender
     * 
     */
    private void cargarTabla() {
    String[] columnas = {"Tipo", "Nombre", "Precio"};

    DefaultTableModel modelo = new DefaultTableModel(columnas, 0);

    for (Animal a : inventario.getAnimales()) {
        modelo.addRow(new Object[]{"Animal", a.getNombre(), a.getPrecio()});
    }

    for (Cultivo c : cultivos.getLista()) {
        modelo.addRow(new Object[]{"Cultivo", c.getNombre(), c.getPrecio()});
    }
    

    jTable1.setModel(modelo);
}
   
    
    private double ajustarPrecio(double precioBase) {
    Random r = new Random();
    double cambio = -0.20 + (0.40 * r.nextDouble());
    return Math.round((precioBase + (precioBase * cambio)) * 100.0) / 100.0;
}

        private void actualizarPrecios() {
    for (Animal a : inventario.getAnimales()) {
        a.setPrecio(ajustarPrecio(a.getPrecio()));
    }

    for (Cultivo c : cultivos.getLista()) {
        c.setPrecio(ajustarPrecio(c.getPrecio()));
    }
}
        private void actualizarIndicadorMercado() {
    Random r = new Random();
    porcentajeMercado = -20 + (40 * r.nextDouble());
double porcentaje = porcentajeMercado;

    String texto = String.format("Precio del mercado: %.2f%%", porcentaje);
    jLabel2.setText(texto);

    if (porcentaje >= 0) {
        jLabel2.setForeground(new java.awt.Color(0, 150, 0)); 
    } else {
        jLabel2.setForeground(java.awt.Color.RED); 
    }
}
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        BtnVender = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setText("Mercado");

        BtnVender.setText("Vender");
        BtnVender.addActionListener(this::BtnVenderActionPerformed);

        jLabel2.setText("Precio del mercado: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnVender)
                            .addComponent(jLabel2))))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnVender)
                        .addGap(46, 46, 46))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnVenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVenderActionPerformed

     
    int fila = jTable1.getSelectedRow();

    if (fila == -1) {
        JOptionPane.showMessageDialog(this, "Selecciona algo");
        return;
    }

    String tipo = jTable1.getValueAt(fila, 0).toString();
    double precio = 0;

    if (tipo.equals("Animal")) {
        Animal a = inventario.getAnimales().get(fila);
        precio = a.getPrecio();
        inventario.getAnimales().remove(fila);
    } else {
        int index = fila - inventario.getAnimales().size();

        if (index < 0 || index >= cultivos.getLista().size()) {
            JOptionPane.showMessageDialog(this, "Error al seleccionar cultivo");
            return;
        }

        Cultivo c = cultivos.getLista().get(index);
        precio = c.getPrecio();
        cultivos.getLista().remove(index);
    }

    double multiplicador = 1 + (porcentajeMercado / 100);
    double precioFinal = precio * multiplicador;

    dinero += precioFinal;

    JOptionPane.showMessageDialog(this,
        "Precio base: $" + precio +
        "\nMercado: " + String.format("%.2f", porcentajeMercado) + "%" +
        "\nGanaste: $" + String.format("%.2f", precioFinal) +
        "\nTotal: $" + String.format("%.2f", dinero)
    );

    cargarTabla();
          // TODO add your handling code here:
    }//GEN-LAST:event_BtnVenderActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
     

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnVender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}